-- Solar Inverters Content: pillar + 2 cluster pages (price, types)
-- Run: psql $POSTGRES_URL < 016-solar-inverters-content.sql

BEGIN;

-- 1. PILLAR: solar-inverters
UPDATE seo_pages SET
  h1 = 'Solar Inverters in India: Types, Prices & Buying Guide',
  meta_title = 'Solar Inverters India: Price, Types & How to Choose | Solar Vipani',
  meta_description = 'Compare solar inverter types — on-grid, off-grid, hybrid and micro inverters. Real prices from verified installers across India. Fill one form, get 2–3 quotes.',
  content = '[
    {
      "heading": "Why the Right Inverter Matters More Than You Think",
      "body": "<p>The solar inverter converts DC electricity from your panels into AC power for your home. It is the single most critical component after the panels themselves — an undersized or poorly matched inverter can cut your system output by 15–25%. With the Indian residential solar market growing 40% year-on-year, choosing the right inverter technology for your setup is the difference between a system that pays for itself in 4 years and one that underperforms for a decade.</p><p>Solar Vipani''s verified installer network across 500+ cities helps you compare inverter options and get quotes matched to your roof and consumption pattern.</p>"
    },
    {
      "heading": "What Is a Solar Inverter?",
      "body": "<p>A solar inverter is an electronic device that converts the direct current (DC) generated by <a href=\"/in/solar-panels/\">solar panels</a> into alternating current (AC) at 230V and 50Hz — the standard used by Indian household appliances and the electricity grid.</p><p>Beyond basic DC-to-AC conversion, modern inverters handle maximum power point tracking (MPPT) to extract peak output from panels, grid synchronisation for net metering, safety disconnection during power outages (anti-islanding), and real-time monitoring via Wi-Fi or Bluetooth apps.</p><p>Inverters typically last 10–15 years — roughly half the lifespan of solar panels — so most homeowners will replace the inverter once during their system''s life.</p>"
    },
    {
      "heading": "Solar Inverter Types at a Glance",
      "body": "<p>There are four main inverter technologies used in Indian residential and commercial solar installations:</p><table><thead><tr><th>Type</th><th>Grid Connection</th><th>Battery Support</th><th>Subsidy Eligible</th><th>Price Range (3kW)</th><th>Best For</th></tr></thead><tbody><tr><td>On-Grid (Grid-Tie)</td><td>Yes</td><td>No</td><td>Yes</td><td>₹18,000–₹35,000</td><td>Most homes, net metering</td></tr><tr><td>Off-Grid</td><td>No</td><td>Yes (required)</td><td>No</td><td>₹25,000–₹45,000</td><td>Remote areas, no grid</td></tr><tr><td>Hybrid</td><td>Yes</td><td>Yes</td><td>Partial</td><td>₹40,000–₹70,000</td><td>Backup + net metering</td></tr><tr><td>Micro Inverter</td><td>Yes</td><td>Optional</td><td>Yes</td><td>₹8,000–₹12,000/panel</td><td>Shaded roofs, max output</td></tr></tbody></table><p>→ <a href=\"/in/solar-inverters/types/\">Full guide: Solar Inverter Types Explained</a></p>"
    },
    {
      "heading": "Solar Inverter Price in India",
      "body": "<p>Inverter cost typically accounts for 20–25% of your total solar system price. Here are current market prices based on quotes from our installer network:</p><table><thead><tr><th>Capacity</th><th>On-Grid</th><th>Off-Grid</th><th>Hybrid</th></tr></thead><tbody><tr><td>1kW</td><td>₹8,000–₹14,000</td><td>₹12,000–₹18,000</td><td>₹18,000–₹28,000</td></tr><tr><td>3kW</td><td>₹18,000–₹35,000</td><td>₹25,000–₹45,000</td><td>₹40,000–₹70,000</td></tr><tr><td>5kW</td><td>₹28,000–₹50,000</td><td>₹40,000–₹65,000</td><td>₹60,000–₹1,00,000</td></tr><tr><td>10kW</td><td>₹50,000–₹90,000</td><td>₹70,000–₹1,20,000</td><td>₹1,00,000–₹1,80,000</td></tr></tbody></table><p>Prices vary by brand, MPPT channels, and monitoring features. Premium brands like Fronius, SMA, and Enphase sit at the top; Indian brands like Havells, Microtek, and UTL offer strong value.</p><p>→ <a href=\"/in/solar-inverters/price/\">Full guide: Solar Inverter Prices in India</a></p>"
    },
    {
      "heading": "On-Grid Inverters",
      "body": "<p>On-grid (grid-tie) inverters are the most popular choice for Indian residential solar — they connect your system to the DISCOM grid and enable net metering. They are also the most affordable inverter type and qualify for PM Surya Ghar subsidy.</p><p>These inverters must perform anti-islanding: they shut down automatically during a grid outage to prevent back-feeding electricity to the grid, which is a safety requirement. This means an on-grid system does not provide backup during power cuts.</p><p>Popular on-grid brands in India include Growatt, Goodwe, Havells, Polycab, and Fronius.</p><p>→ <a href=\"/in/solar-inverters/on-grid/\">Full guide: On-Grid Solar Inverters</a></p>"
    },
    {
      "heading": "Off-Grid Inverters",
      "body": "<p>Off-grid inverters work independently of the electricity grid and require battery banks to store excess solar energy for use at night and on cloudy days. They are the right choice where grid connectivity is unreliable or unavailable — common in rural India and agricultural setups.</p><p>These systems cost 40–60% more than on-grid due to the battery requirement, but they provide complete energy independence. Popular brands include Luminous, Microtek, UTL, and Exide.</p><p>→ <a href=\"/in/solar-inverters/off-grid/\">Full guide: Off-Grid Solar Inverters</a></p>"
    },
    {
      "heading": "Hybrid Inverters",
      "body": "<p>Hybrid inverters combine the best of both worlds — grid connectivity with net metering <em>and</em> battery backup. During the day, they prioritise solar power for your home, send surplus to the grid, and charge batteries. During a power cut, they switch to battery seamlessly.</p><p>They cost 2–3x more than on-grid inverters but are increasingly popular in Indian cities with frequent load-shedding. Leading hybrid brands include Growatt, Goodwe, Deye, and Solis.</p><p>→ <a href=\"/in/solar-inverters/hybrid/\">Full guide: Hybrid Solar Inverters</a></p>"
    },
    {
      "heading": "Micro Inverters",
      "body": "<p>Unlike string inverters (which connect multiple panels to one inverter), micro inverters attach to each individual panel. Each panel operates independently — so shading on one panel does not drag down the others.</p><p>Micro inverters cost 30–50% more per watt but deliver 5–25% higher energy harvest on roofs with partial shading, multiple orientations, or complex layouts. Enphase dominates this segment globally and in India.</p><p>→ <a href=\"/in/solar-inverters/micro-inverter/\">Full guide: Micro Inverters for Solar</a></p>"
    },
    {
      "heading": "Our Installer Network",
      "body": "<p>Solar Vipani connects you with verified solar installers who can recommend the right inverter technology for your specific roof, consumption pattern, and budget. Every installer on our platform carries valid MNRE channel partner certification.</p><ul><li>Verified installers across 500+ districts</li><li>Compare 2–3 quotes with inverter brand and warranty details</li><li>Free consultation, no obligation</li></ul><p><a href=\"/in/get-quotes/\">Get your free solar quotes →</a></p>"
    }
  ]',
  faq = '[
    {
      "question": "Which type of solar inverter is best for home use in India?",
      "answer": "For most Indian homes, an on-grid (grid-tie) inverter is the best choice. It is the most affordable, qualifies for government subsidy, and enables net metering to offset your electricity bill. If you experience frequent power cuts and need backup, a hybrid inverter is worth the extra cost."
    },
    {
      "question": "How long do solar inverters last?",
      "answer": "Solar inverters typically last 10–15 years with proper ventilation and maintenance. Most manufacturers offer a 5–10 year warranty. Since solar panels last 25+ years, plan for one inverter replacement during your system lifetime. Micro inverters tend to last longer (up to 25 years) than string inverters."
    },
    {
      "question": "What size solar inverter do I need?",
      "answer": "Your inverter capacity should match your solar panel array size. For a 3kW panel system, you need a 3kW inverter. Some installers slightly oversize the panel array relative to the inverter (e.g., 3.3kW panels with a 3kW inverter) for better utilisation. Your installer will size the inverter based on your panel layout and consumption."
    },
    {
      "question": "Can I use a solar inverter without batteries?",
      "answer": "Yes — on-grid inverters work without batteries by connecting directly to the electricity grid. You earn net metering credits for surplus power instead of storing it. Off-grid and hybrid inverters can work with batteries, but an on-grid system without batteries is the most cost-effective setup for most Indian homes."
    },
    {
      "question": "What is the price of a 3kW solar inverter in India?",
      "answer": "A 3kW on-grid solar inverter costs ₹18,000–₹35,000 depending on brand and features. Off-grid inverters cost ₹25,000–₹45,000, and hybrid inverters cost ₹40,000–₹70,000 for the same capacity. Indian brands like Havells and Microtek are at the lower end; imported brands like Fronius and SMA at the higher end."
    },
    {
      "question": "Is a hybrid inverter worth the extra cost?",
      "answer": "A hybrid inverter costs 2–3 times more than an on-grid inverter but provides battery backup during power cuts. If your area has reliable grid supply, an on-grid inverter offers better ROI. If you face frequent outages or want energy independence, a hybrid inverter pays for itself through uninterrupted power."
    }
  ]',
  updated_at = NOW()
WHERE slug = 'solar-inverters' AND page_type = 'pillar';


-- 2. CLUSTER: price
UPDATE seo_pages SET
  h1 = 'Solar Inverter Price in India 2026: Complete Price List by Type & Brand',
  meta_title = 'Solar Inverter Price India 2026: On-Grid, Off-Grid & Hybrid Rates | Solar Vipani',
  meta_description = 'Solar inverter prices in India range from ₹8,000 to ₹1,80,000 depending on type and capacity. Compare on-grid, off-grid, hybrid and micro inverter prices by brand.',
  content = '[
    {
      "heading": "The Short Answer",
      "body": "<p>Solar inverter prices in India range from <strong>₹8,000 for a 1kW on-grid inverter</strong> to <strong>₹1,80,000+ for a 10kW hybrid inverter</strong>. The most common residential choice — a 3kW on-grid inverter — costs <strong>₹18,000–₹35,000</strong>. Your inverter typically accounts for 20–25% of total <a href=\"/in/rooftop-solar/cost/\">solar system cost</a>. Price depends primarily on inverter type, capacity, brand, and number of MPPT channels.</p>"
    },
    {
      "heading": "Solar Inverter Price by Type and Capacity",
      "body": "<p>Here are current market prices for each inverter type across common residential and commercial capacities:</p><table><thead><tr><th>Capacity</th><th>On-Grid</th><th>Off-Grid</th><th>Hybrid</th><th>Micro (per panel)</th></tr></thead><tbody><tr><td>1kW</td><td>₹8,000–₹14,000</td><td>₹12,000–₹18,000</td><td>₹18,000–₹28,000</td><td>₹8,000–₹12,000</td></tr><tr><td>2kW</td><td>₹14,000–₹25,000</td><td>₹18,000–₹32,000</td><td>₹30,000–₹50,000</td><td>—</td></tr><tr><td>3kW</td><td>₹18,000–₹35,000</td><td>₹25,000–₹45,000</td><td>₹40,000–₹70,000</td><td>—</td></tr><tr><td>5kW</td><td>₹28,000–₹50,000</td><td>₹40,000–₹65,000</td><td>₹60,000–₹1,00,000</td><td>—</td></tr><tr><td>10kW</td><td>₹50,000–₹90,000</td><td>₹70,000–₹1,20,000</td><td>₹1,00,000–₹1,80,000</td><td>—</td></tr></tbody></table><p><em>Prices include GST. Micro inverter pricing is per-panel unit; a 3kW system with 6 panels would use 6 micro inverters (₹48,000–₹72,000 total).</em></p>"
    },
    {
      "heading": "Why Do Inverter Prices Vary So Much?",
      "body": "<p>Five factors drive the price difference between inverters of the same capacity:</p><ol><li><strong>Inverter type</strong> — On-grid is cheapest (no battery management). Hybrid costs 2–3x more because it includes charger, transfer switch, and battery management system.</li><li><strong>Brand</strong> — European brands (Fronius, SMA) and Enphase command a 30–60% premium over Chinese (Growatt, Goodwe) and Indian (Havells, Microtek) brands.</li><li><strong>MPPT channels</strong> — Single-MPPT inverters are cheaper. Dual-MPPT allows panels on two roof faces to operate independently, improving output by 5–15% on complex roofs.</li><li><strong>Monitoring</strong> — Built-in Wi-Fi with app-based monitoring adds ₹1,000–₹3,000 over basic models. Essential for tracking performance.</li><li><strong>Warranty</strong> — Standard 5-year warranty. Extended 10-year warranty adds ₹3,000–₹8,000 but is recommended given the inverter''s shorter lifespan relative to panels.</li></ol>"
    },
    {
      "heading": "Solar Inverter Price by Brand",
      "body": "<p>Here is how popular <a href=\"/in/solar-inverters/\">solar inverter</a> brands compare for a 3kW on-grid inverter:</p><table><thead><tr><th>Brand</th><th>Origin</th><th>3kW On-Grid Price</th><th>Warranty</th><th>Key Feature</th></tr></thead><tbody><tr><td>Growatt</td><td>China</td><td>₹18,000–₹24,000</td><td>5 years (ext. 10)</td><td>Best value, strong app</td></tr><tr><td>Goodwe</td><td>China</td><td>₹20,000–₹26,000</td><td>5 years (ext. 10)</td><td>Wide voltage range</td></tr><tr><td>Havells</td><td>India</td><td>₹22,000–₹30,000</td><td>5 years</td><td>Local service network</td></tr><tr><td>Polycab</td><td>India</td><td>₹22,000–₹28,000</td><td>5 years</td><td>Trusted Indian brand</td></tr><tr><td>Fronius</td><td>Austria</td><td>₹32,000–₹45,000</td><td>5 years (ext. 10)</td><td>Premium efficiency</td></tr><tr><td>SMA</td><td>Germany</td><td>₹30,000–₹42,000</td><td>5 years (ext. 10)</td><td>Industry benchmark</td></tr><tr><td>Enphase (micro)</td><td>USA</td><td>₹48,000–₹72,000*</td><td>25 years</td><td>Panel-level optimisation</td></tr></tbody></table><p><em>*Enphase price is total for 6 micro inverters in a 3kW system.</em></p><p>For most Indian residential installations, Growatt and Goodwe offer the best balance of price, performance, and after-sales support.</p>"
    },
    {
      "heading": "On-Grid vs Off-Grid vs Hybrid: Price Comparison",
      "body": "<p>The price gap between inverter types widens as capacity increases:</p><ul><li><strong><a href=\"/in/solar-inverters/on-grid/\">On-grid inverters</a></strong> are 40–60% cheaper than hybrid. They qualify for <a href=\"/in/solar-subsidy/pm-surya-ghar/\">PM Surya Ghar subsidy</a> and are the default choice for net metering setups.</li><li><strong><a href=\"/in/solar-inverters/off-grid/\">Off-grid inverters</a></strong> cost 30–50% more than on-grid because they include battery charger and management circuits. Add battery cost (₹40,000–₹1,50,000) for the complete off-grid setup.</li><li><strong><a href=\"/in/solar-inverters/hybrid/\">Hybrid inverters</a></strong> are the most expensive string inverter option. They combine grid-tie, battery charger, and automatic transfer switch in one unit. The premium is justified if you need backup during outages.</li></ul><p>Choose on-grid unless you have a specific reason for batteries. The money saved on a simpler inverter is better spent on more or higher-quality panels.</p>"
    },
    {
      "heading": "How Inverter Cost Fits Into Total System Price",
      "body": "<p>Your inverter is one component of the total <a href=\"/in/rooftop-solar/cost/\">rooftop solar system cost</a>. Here is the typical cost breakdown for a 3kW on-grid system:</p><table><thead><tr><th>Component</th><th>Share of Total Cost</th><th>Approx. Cost (3kW)</th></tr></thead><tbody><tr><td><a href=\"/in/solar-panels/price/\">Solar Panels</a></td><td>40–50%</td><td>₹65,000–₹95,000</td></tr><tr><td>Solar Inverter</td><td>20–25%</td><td>₹18,000–₹35,000</td></tr><tr><td>Mounting Structure</td><td>10–15%</td><td>₹12,000–₹22,000</td></tr><tr><td>Wiring & Electrical</td><td>5–8%</td><td>₹8,000–₹14,000</td></tr><tr><td>Installation Labour</td><td>5–10%</td><td>₹8,000–₹15,000</td></tr><tr><td>Net Metering & Approvals</td><td>2–5%</td><td>₹3,000–₹8,000</td></tr></tbody></table><p>Upgrading from a budget to a premium inverter adds ₹10,000–₹20,000 to a 3kW system — a modest increase for potentially better efficiency and longevity.</p>"
    },
    {
      "heading": "Tips to Get the Best Inverter Price",
      "body": "<ul><li><strong>Compare 2–3 quotes</strong> — Inverter markups vary significantly between installers. Solar Vipani''s <a href=\"/in/get-quotes/\">free quote service</a> lets you compare itemised breakdowns.</li><li><strong>Check warranty terms</strong> — A ₹3,000 extended warranty is cheap insurance for a component that lasts 10–15 years.</li><li><strong>Right-size the inverter</strong> — Don''t oversize. A 3kW inverter for a 3kW panel array is standard. Slight panel oversizing (3.3kW panels, 3kW inverter) improves utilisation.</li><li><strong>Prioritise MPPT count</strong> — If your roof has panels on two faces (east + west, or partially shaded), a dual-MPPT inverter justifies its premium.</li><li><strong>Factor in monitoring</strong> — Wi-Fi-enabled inverters let you track daily output and spot issues early. Worth the ₹1,000–₹3,000 premium.</li></ul>"
    },
    {
      "heading": "Get Accurate Inverter Quotes for Your Roof",
      "body": "<p>Online price lists give you a range. For an exact number, you need quotes tailored to your system size, panel layout, and grid connection requirements.</p><p>Solar Vipani connects you with 2–3 verified local installers who provide itemised quotes — including inverter brand, model, warranty, and monitoring details — free and without obligation.</p><p><a href=\"/in/get-quotes/\">Get your free solar quotes →</a></p>"
    }
  ]',
  faq = '[
    {
      "question": "What is the price of a 5kW solar inverter in India?",
      "answer": "A 5kW on-grid solar inverter costs ₹28,000–₹50,000 in India. Off-grid 5kW inverters cost ₹40,000–₹65,000, and hybrid 5kW inverters cost ₹60,000–₹1,00,000. Budget brands like Growatt start at the lower end, while premium brands like Fronius are at the higher end."
    },
    {
      "question": "Which solar inverter brand is best in India?",
      "answer": "Growatt and Goodwe offer the best value for most residential installations — reliable performance at competitive prices with good app-based monitoring. For premium setups, Fronius and SMA deliver top-tier efficiency. Enphase is the leader for micro inverters. Indian brands Havells and Polycab offer strong local service support."
    },
    {
      "question": "Is a micro inverter worth the extra cost?",
      "answer": "Micro inverters cost 30–50% more per watt than string inverters but deliver 5–25% more energy on roofs with partial shading or multiple orientations. If your roof is shade-free with uniform panel orientation, a string inverter offers better value. If you have shading or a complex roof layout, micro inverters pay for themselves over time."
    },
    {
      "question": "Does the solar inverter price include installation?",
      "answer": "Inverter prices quoted by manufacturers or online stores are for the unit only. When you get a complete solar system quote from an installer, the inverter cost is bundled with panels, mounting, wiring, and installation labour. Always compare itemised quotes to understand the inverter cost within the total system price."
    },
    {
      "question": "Should I buy the cheapest solar inverter available?",
      "answer": "No. The inverter is the component most likely to fail in a solar system. Saving ₹5,000–₹10,000 on a budget inverter can cost you more in lost generation, earlier replacement, and no monitoring. Mid-range brands like Growatt, Goodwe, or Havells offer the best balance of price and reliability for Indian conditions."
    }
  ]',
  updated_at = NOW()
WHERE slug = 'price' AND pillar_slug = 'solar-inverters';


-- 3. CLUSTER: types
UPDATE seo_pages SET
  h1 = 'Types of Solar Inverters: On-Grid, Off-Grid, Hybrid & Micro Explained',
  meta_title = 'Solar Inverter Types: On-Grid vs Off-Grid vs Hybrid vs Micro | Solar Vipani',
  meta_description = 'Compare 4 solar inverter types — on-grid, off-grid, hybrid and micro inverters. Learn which type suits your home, budget, and power backup needs in India.',
  content = '[
    {
      "heading": "The Short Answer",
      "body": "<p>There are four main types of <a href=\"/in/solar-inverters/\">solar inverters</a> used in India: <strong>on-grid</strong> (grid-tie), <strong>off-grid</strong>, <strong>hybrid</strong>, and <strong>micro inverters</strong>. On-grid inverters are the most affordable and popular for homes with reliable grid supply. Off-grid inverters work with batteries for areas without grid. Hybrid inverters combine grid-tie with battery backup. Micro inverters optimise each panel individually. Your choice depends on grid reliability, backup needs, and budget.</p>"
    },
    {
      "heading": "On-Grid (Grid-Tie) Inverters",
      "body": "<p>On-grid inverters connect your solar system to the electricity grid and enable <a href=\"/in/solar-subsidy/net-metering/\">net metering</a>. They are the simplest, most affordable, and most widely installed inverter type in India.</p><p><strong>How they work:</strong> Panels generate DC power → inverter converts to AC → your home uses solar power first → surplus feeds into the grid → DISCOM credits your account via net metering.</p><p><strong>Key features:</strong></p><ul><li>No batteries needed — the grid acts as your virtual storage</li><li>Anti-islanding protection — shuts down during grid outages for safety</li><li>Qualifies for <a href=\"/in/solar-subsidy/pm-surya-ghar/\">PM Surya Ghar subsidy</a></li><li>Highest efficiency (96–98%) among all inverter types</li><li>Lowest cost: ₹18,000–₹35,000 for 3kW</li></ul><p><strong>Limitation:</strong> Does not provide power during grid outages. If backup is critical, consider hybrid.</p><p>→ <a href=\"/in/solar-inverters/on-grid/\">Complete on-grid inverter guide</a></p>"
    },
    {
      "heading": "Off-Grid Inverters",
      "body": "<p>Off-grid inverters operate independently of the electricity grid. They work with battery banks to store solar energy for use when panels are not generating — at night, on cloudy days, and during any time of day.</p><p><strong>How they work:</strong> Panels generate DC → inverter charges batteries and converts DC to AC → batteries supply power when panels cannot.</p><p><strong>Key features:</strong></p><ul><li>Complete energy independence — no grid dependency</li><li>Built-in charge controller for battery management</li><li>Essential for remote locations without grid access</li><li>Cost: ₹25,000–₹45,000 for 3kW (plus battery cost of ₹40,000–₹1,50,000)</li></ul><p><strong>Limitations:</strong> Higher total cost due to batteries. No net metering benefit. Batteries need replacement every 5–8 years (lead-acid) or 10–15 years (lithium).</p><p>→ <a href=\"/in/solar-inverters/off-grid/\">Complete off-grid inverter guide</a></p>"
    },
    {
      "heading": "Hybrid Inverters",
      "body": "<p>Hybrid inverters combine on-grid and off-grid functionality in a single unit. They connect to the grid for net metering while also managing a battery bank for backup during power cuts.</p><p><strong>How they work:</strong> Panels generate DC → inverter prioritises: (1) power your home, (2) charge battery, (3) export surplus to grid. During outage → inverter switches to battery seamlessly.</p><p><strong>Key features:</strong></p><ul><li>Net metering + battery backup in one device</li><li>Automatic switchover during power cuts (10–20ms, imperceptible)</li><li>Can be installed without battery initially and upgraded later</li><li>Cost: ₹40,000–₹70,000 for 3kW (plus battery)</li></ul><p><strong>Best for:</strong> Indian cities with frequent load-shedding where you want both bill savings and uninterrupted power.</p><p>→ <a href=\"/in/solar-inverters/hybrid/\">Complete hybrid inverter guide</a></p>"
    },
    {
      "heading": "Micro Inverters",
      "body": "<p>Unlike string inverters (on-grid, off-grid, hybrid) that connect multiple panels to one central inverter, micro inverters are small units attached to each individual panel. Each panel operates independently with its own DC-to-AC conversion.</p><p><strong>How they work:</strong> Each panel has its own micro inverter → AC output from all panels combines at the distribution board → feeds home and grid.</p><p><strong>Key features:</strong></p><ul><li>Panel-level optimisation — shading on one panel does not affect others</li><li>5–25% higher energy harvest on shaded or complex roofs</li><li>Longer warranty: 25 years (vs 5–10 for string inverters)</li><li>Easier system expansion — add panels one at a time</li><li>Cost: ₹8,000–₹12,000 per panel (₹48,000–₹72,000 for a 6-panel/3kW system)</li></ul><p><strong>Best for:</strong> Roofs with partial shading, multiple orientations (east + west), or where maximum energy harvest justifies the premium.</p><p>→ <a href=\"/in/solar-inverters/micro-inverter/\">Complete micro inverter guide</a></p>"
    },
    {
      "heading": "String Inverters vs Micro Inverters",
      "body": "<p>This is the most common comparison buyers face. Here is a side-by-side:</p><table><thead><tr><th>Feature</th><th>String Inverter</th><th>Micro Inverter</th></tr></thead><tbody><tr><td>Architecture</td><td>1 inverter for all panels</td><td>1 inverter per panel</td></tr><tr><td>Cost (3kW)</td><td>₹18,000–₹35,000</td><td>₹48,000–₹72,000</td></tr><tr><td>Shading impact</td><td>One shaded panel affects entire string</td><td>Only the shaded panel is affected</td></tr><tr><td>Efficiency (no shade)</td><td>96–98%</td><td>95–97%</td></tr><tr><td>Monitoring</td><td>System-level</td><td>Panel-level</td></tr><tr><td>Warranty</td><td>5–10 years</td><td>25 years</td></tr><tr><td>Maintenance</td><td>Central unit — easy access</td><td>Roof-mounted — harder access</td></tr></tbody></table><p><strong>Rule of thumb:</strong> If your roof is shade-free and panels face one direction, a string inverter is the better value. If you have shading, multiple roof angles, or want maximum long-term yield, micro inverters justify the premium.</p>"
    },
    {
      "heading": "How to Choose the Right Inverter Type",
      "body": "<p>Use this decision framework:</p><ol><li><strong>Do you have reliable grid supply?</strong> → Yes: On-grid or hybrid. No: Off-grid.</li><li><strong>Do you need power during outages?</strong> → Yes: Hybrid. No: On-grid.</li><li><strong>Is your roof partially shaded?</strong> → Yes: Consider micro inverters. No: String inverter is fine.</li><li><strong>What is your budget?</strong> → Tight: On-grid string. Moderate: Hybrid. Premium: Micro inverters.</li><li><strong>Do you want government subsidy?</strong> → On-grid and micro inverter systems qualify for PM Surya Ghar subsidy. Off-grid does not.</li></ol><p>Most Indian homeowners in urban areas with reliable grid: <strong>on-grid string inverter</strong>. Urban areas with frequent power cuts: <strong>hybrid</strong>. Complex or shaded roofs: <strong>micro inverters</strong>.</p><p>→ <a href=\"/in/tools/solar-calculator/\">Use our solar calculator to estimate your needs</a></p>"
    },
    {
      "heading": "Compare Inverter Options for Your Home",
      "body": "<p>The right inverter depends on your roof, grid conditions, and energy goals. Solar Vipani''s verified installers will assess your setup and recommend the optimal inverter type and brand for your needs — with itemised quotes so you can compare.</p><p><a href=\"/in/get-quotes/\">Get your free solar quotes →</a></p>"
    }
  ]',
  faq = '[
    {
      "question": "What is the difference between on-grid and off-grid solar inverters?",
      "answer": "On-grid inverters connect to the electricity grid and enable net metering — surplus solar power earns credits on your bill. They do not work during power cuts. Off-grid inverters work independently with battery storage, providing power even without grid. On-grid is cheaper and suits urban homes; off-grid suits remote areas without reliable grid."
    },
    {
      "question": "Can I convert an on-grid inverter to hybrid later?",
      "answer": "No. On-grid and hybrid inverters are fundamentally different hardware — you cannot retrofit an on-grid inverter with battery support. However, some hybrid inverters can be installed without batteries initially and have batteries added later. If you think you may want backup in the future, invest in a hybrid inverter upfront."
    },
    {
      "question": "Which solar inverter type is most efficient?",
      "answer": "On-grid string inverters are the most efficient at 96–98% conversion efficiency because they have the simplest architecture with no battery management overhead. Hybrid inverters achieve 94–97%. Micro inverters achieve 95–97% per panel but can deliver higher total system yield on shaded roofs due to panel-level optimisation."
    },
    {
      "question": "Do I need a hybrid inverter if my area has power cuts?",
      "answer": "If power cuts are rare (a few hours per month), an on-grid inverter with a basic UPS for critical loads may suffice. If power cuts are frequent or prolonged, a hybrid inverter with battery backup is the better investment — it provides seamless switchover and continues powering your home using stored solar energy."
    },
    {
      "question": "Are micro inverters available in India?",
      "answer": "Yes. Enphase is the dominant micro inverter brand in India and has a growing installer network. APsystems is another option. Micro inverters are available through most verified solar installers but may have longer lead times than string inverters. Prices run ₹8,000–₹12,000 per panel unit."
    }
  ]',
  updated_at = NOW()
WHERE slug = 'types' AND pillar_slug = 'solar-inverters';

COMMIT;
