import { db } from './db';
import { geoLocations, businessProfiles } from '@solar/db/schema';
import { and, asc, count, countDistinct, desc, eq, sql } from 'drizzle-orm';

export type TopDistrict = {
	name: string;
	state: string;
	stateSlug: string;
	districtSlug: string;
	installerCount: number;
};

export type DistrictWithInstallerCount = {
	state: string;
	district: string;
	slug: string;
	stateSlug: string;
	installerCount: number;
};

// Every IN district, each with its visible-installer count. Shared by the
// solar-calculator and subsidy-checker tools, which built this identically.
//
// The counts come from a second, grouped query rather than a join so that
// districts with no installers still appear — the tools list all of them.
export async function getDistrictsWithInstallerCounts(): Promise<DistrictWithInstallerCount[]> {
	const [districtRows, countRows] = await Promise.all([
		db
			.selectDistinct({
				state: geoLocations.level1,
				district: geoLocations.level2,
				stateSlug: geoLocations.level1Slug,
				districtSlug: geoLocations.level2Slug
			})
			.from(geoLocations)
			.where(eq(geoLocations.countryCode, 'in'))
			.orderBy(asc(geoLocations.level1), asc(geoLocations.level2)),
		db
			.select({
				state: sql<string>`LOWER(${businessProfiles.state})`,
				district: sql<string>`LOWER(${businessProfiles.district})`,
				cnt: count()
			})
			.from(businessProfiles)
			.where(eq(businessProfiles.isvisible, true))
			.groupBy(sql`LOWER(${businessProfiles.state})`, sql`LOWER(${businessProfiles.district})`)
	]);

	const countMap = new Map<string, number>();
	for (const r of countRows) {
		countMap.set(`${r.state}|${r.district}`, Number(r.cnt));
	}

	// geo_locations columns are all NOT NULL, and its slugs were generated by
	// sv_slugify — the same lower-case/whitespace-to-hyphen convention the
	// callers used to compute here (042).
	return districtRows.map((r) => ({
		state: r.state,
		district: r.district,
		slug: r.districtSlug,
		stateSlug: r.stateSlug,
		installerCount: countMap.get(`${r.state.toLowerCase()}|${r.district.toLowerCase()}`) || 0
	}));
}

export async function getVisibleInstallerCount(): Promise<number> {
	const rows = await db
		.select({ total: count() })
		.from(businessProfiles)
		.where(eq(businessProfiles.isvisible, true));
	return rows[0]?.total ?? 0;
}

export async function getTopDistricts(limit = 5): Promise<TopDistrict[]> {
	const installerCount = countDistinct(businessProfiles.businessId);

	const rows = await db
		.select({
			district: geoLocations.level2,
			state: geoLocations.level1,
			stateSlug: geoLocations.level1Slug,
			districtSlug: geoLocations.level2Slug,
			installerCount
		})
		.from(geoLocations)
		.innerJoin(
			businessProfiles,
			and(
				sql`lower(${businessProfiles.district}) = lower(${geoLocations.level2})`,
				eq(businessProfiles.isvisible, true)
			)
		)
		.where(eq(geoLocations.countryCode, 'in'))
		.groupBy(
			geoLocations.level2,
			geoLocations.level1,
			geoLocations.level1Slug,
			geoLocations.level2Slug
		)
		.orderBy(desc(installerCount))
		.limit(limit);

	return rows.map((r) => ({
		name: r.district,
		state: r.state,
		stateSlug: r.stateSlug,
		districtSlug: r.districtSlug,
		installerCount: r.installerCount
	}));
}
