-- GENERATED by scripts/generate-test-baseline.mjs — do not hand-edit.
--
-- Table DDL for the integration test database, exported from packages/db/src/schema
-- (which drizzle-kit pull produces from the live database). Applied by the test
-- global setup before the numbered SQL migrations replay on top of it.
--
-- Regenerate after a schema change:
--   npm run pull -w @solar/db && node scripts/generate-test-baseline.mjs

CREATE SCHEMA "embeddings";

CREATE SEQUENCE "public"."personal_website_blogs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;
CREATE TABLE "authors" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(100) NOT NULL,
	"name" varchar(200) NOT NULL,
	"photo_url" text,
	"credentials" text,
	"expertise" text,
	"bio" text,
	"social_links" jsonb,
	"status" varchar(20) DEFAULT 'published',
	CONSTRAINT "authors_slug_key" UNIQUE("slug")
);

CREATE TABLE "branches" (
	"id" serial PRIMARY KEY NOT NULL,
	"main_id" integer NOT NULL,
	"branch_id" integer NOT NULL,
	"isactive" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now()
);

CREATE TABLE "business_accounts" (
	"id" serial PRIMARY KEY NOT NULL,
	"country_code" char(2) NOT NULL,
	"source_id" integer NOT NULL,
	"login_email" varchar(255),
	"login_password" varchar(255),
	"magic_link_token" text,
	"magic_link_token_expires_at" timestamp with time zone,
	"reset_token" varchar(255),
	"reset_token_expires" timestamp,
	"isvisible" boolean,
	"last_login" timestamp,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "business_accounts_country_code_source_id_key" UNIQUE("country_code","source_id")
);

CREATE TABLE "business_profiles" (
	"id" serial PRIMARY KEY NOT NULL,
	"business_id" serial NOT NULL,
	"slug" varchar(255),
	"businessname" varchar(255),
	"email" varchar(255),
	"phonenumber" varchar(20),
	"whatsapp" varchar(20),
	"description" varchar(256),
	"website" varchar(255),
	"instagram_id" varchar(255),
	"google_maps_link" varchar(255),
	"address" text,
	"pluscode" varchar(255),
	"services" integer[],
	"brands" integer[],
	"tax_id" varchar(50),
	"level1" varchar(100),
	"level2" varchar(100),
	"city" varchar(100),
	"postal_code" varchar(10),
	"rscore" integer,
	"tag" varchar(255),
	"notes" text,
	"businessfilled" boolean,
	"tier3" boolean,
	"isvisible" boolean,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"country_code" char(2) DEFAULT 'in' NOT NULL,
	CONSTRAINT "business_profiles_business_id_key" UNIQUE("business_id")
);

CREATE TABLE "callsafe_email_campaign_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"business_id" integer,
	"recipient_email" text,
	"website" text,
	"country" text,
	"email_number" integer,
	"campaign_run_id" text,
	"sent_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "callsafe_masterlist" (
	"id" serial PRIMARY KEY NOT NULL,
	"website" varchar NOT NULL,
	"country" varchar NOT NULL,
	"recipient_email" varchar,
	"phone_number" varchar,
	"verified" integer DEFAULT 0,
	"unsubscribe" integer DEFAULT 0,
	"number_of_emails_sent" integer DEFAULT 0,
	"earlier_date" date,
	"earlier_to_earlier_date" date,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "callsafe_unsubscribe" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "callsafe_unsubscribe_email_key" UNIQUE("email")
);

CREATE TABLE "callsafehandles" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"handle" varchar(30) NOT NULL,
	"is_embedded" boolean DEFAULT false,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "callsafeusers" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"is_active" boolean DEFAULT true,
	"sourceid" varchar(30),
	"isembedded" boolean DEFAULT false,
	CONSTRAINT "callsafeusers_email_key" UNIQUE("email")
);

CREATE TABLE "chatbotmessagecount" (
	"id" serial PRIMARY KEY NOT NULL,
	"ip" varchar(45) NOT NULL,
	"date" date NOT NULL,
	"count" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "unique_ip_date" UNIQUE("ip","date")
);

CREATE TABLE "chatbotmessagesstore" (
	"id" serial PRIMARY KEY NOT NULL,
	"ip" varchar(45) NOT NULL,
	"timestamp" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"message_type" varchar(10) NOT NULL,
	"message_content" text NOT NULL,
	"session_id" varchar(100),
	"processing_time_ms" integer,
	"tokens_used" integer,
	"metadata" jsonb,
	CONSTRAINT "chatbotmessagesstore_message_type_check" CHECK ((message_type)::text = ANY ((ARRAY['user'::character varying, 'assistant'::character varying])::text[]))
);

CREATE TABLE "claimdata" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"phone" varchar(16) NOT NULL,
	"email" varchar(255) NOT NULL,
	"message" text NOT NULL,
	"business_slug" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"isresolved" boolean DEFAULT false
);

CREATE TABLE "contact_us_form" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"phone" varchar(20) NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "countries" (
	"code" char(2) PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);

CREATE TABLE "data_access_requests" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"phone" text,
	"reason" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "data_deletion_requests" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"phone" varchar(20),
	"reason" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"status" varchar(50) DEFAULT 'pending',
	"processed_at" timestamp,
	"notes" text
);

CREATE TABLE "discoms" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(100) NOT NULL,
	"name" varchar(200) NOT NULL,
	"state_slug" varchar(100),
	"net_metering_policy" text,
	"tariff_structure" text,
	"application_process" text,
	"content" jsonb,
	"faq" jsonb,
	"status" varchar(20) DEFAULT 'draft',
	CONSTRAINT "discoms_slug_key" UNIQUE("slug")
);

CREATE TABLE "geo_locations" (
	"id" serial PRIMARY KEY NOT NULL,
	"country_code" char(2) NOT NULL,
	"level1" varchar(255) NOT NULL,
	"level2" varchar(255) NOT NULL,
	"city" varchar(255) NOT NULL,
	"level1_slug" varchar(255) NOT NULL,
	"level2_slug" varchar(255) NOT NULL,
	"city_slug" varchar(255) NOT NULL,
	CONSTRAINT "geo_locations_country_code_level1_slug_level2_slug_city_slu_key" UNIQUE("country_code","level1_slug","level2_slug","city_slug")
);

CREATE TABLE "idea_pot" (
	"id" serial PRIMARY KEY NOT NULL,
	"idea" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"notes" char(255),
	"isvisible" boolean DEFAULT true,
	"category" varchar(255) DEFAULT NULL
);

CREATE TABLE "in_blog_posts" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(255) NOT NULL,
	"title" varchar(300) NOT NULL,
	"meta_title" varchar(160),
	"meta_description" varchar(320),
	"content" text NOT NULL,
	"author_slug" varchar(100),
	"parent_cluster_slug" varchar(255),
	"tags" jsonb,
	"published_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now(),
	"status" varchar(20) DEFAULT 'draft',
	CONSTRAINT "in_blog_posts_slug_key" UNIQUE("slug")
);

CREATE TABLE "in_proposals" (
	"id" serial PRIMARY KEY NOT NULL,
	"customer_name" varchar(255) NOT NULL,
	"phone_number" varchar(20),
	"address" text,
	"email" varchar(255),
	"system_capacity_kw" numeric(10, 2) NOT NULL,
	"panels_brand_model" varchar(255),
	"number_of_panels" integer,
	"inverter_brand_model" varchar(255),
	"notes" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"lead_id" integer,
	"business_slug" varchar(255) NOT NULL
);

CREATE TABLE "in_user" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"name" varchar(255),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"magic_link_token" varchar(255),
	"last_login" timestamp,
	"feedback_email_sent_at" timestamp,
	"magic_link_token_expires_at" timestamp with time zone,
	CONSTRAINT "users_email_key" UNIQUE("email")
);

CREATE TABLE "in_user_feedback" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"got_callback" boolean NOT NULL,
	"got_quotation" boolean NOT NULL,
	"recommendation_rating" smallint NOT NULL,
	"suggestions" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "in_user_feedback_user_id_key" UNIQUE("user_id"),
	CONSTRAINT "in_user_feedback_recommendation_rating_check" CHECK ((recommendation_rating >= 1) AND (recommendation_rating <= 5))
);

CREATE TABLE "installer_invitation_email_campaign_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"db_table" varchar(100) NOT NULL,
	"business_id" integer NOT NULL,
	"recipient_email" varchar(255) NOT NULL,
	"vendor_name" varchar(255),
	"state" varchar(100),
	"email_number" integer,
	"campaign_run_id" varchar(50) NOT NULL,
	"sent_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE "leaddata" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"phone" varchar(16) NOT NULL,
	"postal_code" varchar(10) NOT NULL,
	"type" varchar(510),
	"comment" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"svnotes" text,
	"urlparams" varchar(255) DEFAULT NULL,
	"isvisible" boolean DEFAULT true,
	"email" varchar(255),
	"category" smallint,
	"level2" varchar(255),
	"stage" smallint DEFAULT 0,
	"status" boolean DEFAULT true,
	"claim_count" smallint DEFAULT 0,
	"original_id" integer,
	"business_id" integer,
	"email_invite_count" integer DEFAULT 0,
	"sv_comment_for_businesses" text,
	"reference_uuid" uuid DEFAULT gen_random_uuid(),
	"business_notes" text,
	"level1" varchar(100),
	"qualification_score" integer,
	"bill_url" text,
	"bill_cloudinary_public_id" text,
	"bill_format" text,
	"bill_uploaded_at" timestamp with time zone,
	"marketing_consent" boolean DEFAULT false NOT NULL,
	"country_code" char(2) DEFAULT 'in' NOT NULL,
	CONSTRAINT "check_claim_count_limit" CHECK ((claim_count >= 0) AND (claim_count <= 5))
);

CREATE TABLE "leaddata_claimrequests" (
	"id" serial PRIMARY KEY NOT NULL,
	"lead_id" serial NOT NULL,
	"claim_id" serial NOT NULL,
	"business_id" smallint,
	"isallotted" boolean DEFAULT false,
	"isresolved" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "unique_lead_business_claim" UNIQUE("lead_id","business_id")
);

CREATE TABLE "legal_acceptances" (
	"id" serial PRIMARY KEY NOT NULL,
	"business_id" integer NOT NULL,
	"policy_id" integer NOT NULL,
	"accepted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_address" varchar(45),
	"country_code" char(2) NOT NULL
);

CREATE TABLE "legal_policies" (
	"id" serial PRIMARY KEY NOT NULL,
	"type" varchar(50) NOT NULL,
	"version" varchar(20) NOT NULL,
	"summary" text NOT NULL,
	"effective_at" timestamp with time zone NOT NULL,
	CONSTRAINT "legal_policies_type_version_key" UNIQUE("type","version")
);

CREATE TABLE "masterlist_indian_businesses" (
	"id" serial PRIMARY KEY NOT NULL,
	"state" varchar(100),
	"vendor_name" varchar(255) NOT NULL,
	"recipient_email" varchar(255) NOT NULL,
	"verified" integer DEFAULT 0,
	"earlier_date" date,
	"unsubscribe" integer DEFAULT 0,
	"contact_person" varchar(255),
	"mobile_number" varchar(20),
	"earlier_to_earlier_date" date,
	"number_of_emails_sent" integer DEFAULT 0,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"empanelled_vendor" integer DEFAULT 0,
	"rating" numeric(2, 1),
	"installed_capacity" integer,
	"website" text,
	"address" text,
	"vendor_id" integer,
	"district" text,
	"district_id" integer,
	"location_source" text,
	CONSTRAINT "unique_recipient_email" UNIQUE("recipient_email"),
	CONSTRAINT "check_verified" CHECK (verified = ANY (ARRAY[0, 1])),
	CONSTRAINT "check_unsubscribe" CHECK (unsubscribe = ANY (ARRAY[0, 1])),
	CONSTRAINT "check_emails_sent" CHECK (number_of_emails_sent >= 0),
	CONSTRAINT "check_empanelled" CHECK (empanelled_vendor = ANY (ARRAY[0, 1]))
);

CREATE TABLE "masterlist_usa_businesses" (
	"id" serial PRIMARY KEY NOT NULL,
	"state" varchar(100) NOT NULL,
	"vendor_name" varchar(255) NOT NULL,
	"recipient_email" varchar(255) NOT NULL,
	"verified" integer DEFAULT 0,
	"earlier_date" date,
	"unsubscribe" integer DEFAULT 0,
	"contact_person" varchar(255),
	"mobile_number" varchar(20),
	"earlier_to_earlier_date" date,
	"number_of_emails_sent" integer DEFAULT 0,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"county" varchar(100),
	"google_maps_url" text,
	"website" varchar(255),
	CONSTRAINT "check_verified_usa" CHECK (verified = ANY (ARRAY[0, 1])),
	CONSTRAINT "check_emails_sent_usa" CHECK (number_of_emails_sent >= 0),
	CONSTRAINT "check_unsubscribe_usa" CHECK (unsubscribe = ANY (ARRAY[0, 1]))
);

CREATE TABLE "masterlist_vendor_district_coverage" (
	"vendor_id" integer NOT NULL,
	"state_id" integer NOT NULL,
	"state" text NOT NULL,
	"district_id" integer NOT NULL,
	"district" text NOT NULL,
	"installation_count" integer DEFAULT 0 NOT NULL,
	"installed_capacity" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "masterlist_vendor_district_coverage_pkey" PRIMARY KEY("vendor_id","district_id")
);

CREATE TABLE "pincode_mapping" (
	"id" serial PRIMARY KEY NOT NULL,
	"pincode" char(6) NOT NULL,
	"district" varchar(255) NOT NULL,
	"state" varchar(100)
);

CREATE TABLE "project_management" (
	"id" serial PRIMARY KEY NOT NULL,
	"lead_id" integer NOT NULL,
	"stage" smallint DEFAULT 1,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"last_updated" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "projects" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"pincode" varchar(20) NOT NULL,
	"project_date" date NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"image_path" varchar(255),
	"image_url" varchar(255),
	"cloudinary_public_id" varchar(255),
	"image_width" integer,
	"image_height" integer,
	"image_format" varchar(10),
	"business_slug" varchar(255),
	"isvisible" boolean DEFAULT true,
	"project_slug" varchar(255),
	"district" varchar(100),
	"city" varchar(100)
);

CREATE TABLE "queries" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"phone" varchar(16) NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	"pincode" integer,
	"notes" varchar(255),
	"urlparam" varchar(255)
);

CREATE TABLE "rate_limits" (
	"identifier" text PRIMARY KEY NOT NULL,
	"count" integer DEFAULT 0 NOT NULL,
	"reset_time" timestamp with time zone NOT NULL
);

CREATE TABLE "seo_pages" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(255) NOT NULL,
	"pillar_slug" varchar(100),
	"page_type" varchar(50) NOT NULL,
	"product_category" varchar(50),
	"h1" text NOT NULL,
	"meta_title" varchar(160) NOT NULL,
	"meta_description" varchar(320) NOT NULL,
	"content" jsonb NOT NULL,
	"faq" jsonb,
	"author_slug" varchar(100),
	"status" varchar(20) DEFAULT 'draft',
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "seo_pages_slug_pillar_unique" UNIQUE("slug","pillar_slug")
);

CREATE TABLE "server_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"timestamp" timestamp NOT NULL,
	"method" varchar(10),
	"url" text,
	"status_code" integer,
	"response_time" double precision,
	"user_agent" text,
	"referrer" text,
	"error_message" text
);

CREATE TABLE "solar_brands" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(100) NOT NULL,
	"name" varchar(200) NOT NULL,
	"product_category" varchar(50) NOT NULL,
	"description" text,
	"logo_url" text,
	"meta_title" varchar(160),
	"meta_description" varchar(320),
	"faq" jsonb,
	"status" varchar(20) DEFAULT 'draft',
	CONSTRAINT "solar_brands_slug_key" UNIQUE("slug")
);

CREATE TABLE "solar_financing_banks" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(100) NOT NULL,
	"name" varchar(200) NOT NULL,
	"interest_rate" text,
	"max_amount" text,
	"tenure" text,
	"eligibility" text,
	"documents" text,
	"content" jsonb,
	"faq" jsonb,
	"status" varchar(20) DEFAULT 'draft',
	CONSTRAINT "solar_financing_banks_slug_key" UNIQUE("slug")
);

CREATE TABLE "solar_products" (
	"id" serial PRIMARY KEY NOT NULL,
	"brand_slug" varchar(100),
	"model_slug" varchar(100) NOT NULL,
	"name" varchar(200) NOT NULL,
	"product_category" varchar(50) NOT NULL,
	"specs" jsonb NOT NULL,
	"price_range_min" integer,
	"price_range_max" integer,
	"datasheet_url" text,
	"status" varchar(20) DEFAULT 'draft',
	CONSTRAINT "solar_products_brand_slug_model_slug_key" UNIQUE("brand_slug","model_slug")
);

CREATE TABLE "state_subsidies" (
	"id" serial PRIMARY KEY NOT NULL,
	"state_slug" varchar(100) NOT NULL,
	"state_name" varchar(100) NOT NULL,
	"central_subsidy_rate" text,
	"state_topup_rate" text,
	"eligibility" text,
	"application_process" text,
	"content" jsonb,
	"faq" jsonb,
	"last_verified" date,
	"status" varchar(20) DEFAULT 'draft',
	CONSTRAINT "state_subsidies_state_slug_key" UNIQUE("state_slug")
);

CREATE TABLE "unsubscribe" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "embeddings"."in_embedding_index" (
	"id" serial PRIMARY KEY NOT NULL,
	"page_link" text NOT NULL,
	"last_update" timestamp,
	"chunking_strategy" text,
	"last_embedding_update" timestamp
);

ALTER TABLE "business_accounts" ADD CONSTRAINT "business_accounts_country_code_fkey" FOREIGN KEY ("country_code") REFERENCES "public"."countries"("code") ON DELETE no action ON UPDATE no action;
ALTER TABLE "business_profiles" ADD CONSTRAINT "business_profiles_country_code_fkey" FOREIGN KEY ("country_code") REFERENCES "public"."countries"("code") ON DELETE no action ON UPDATE no action;
ALTER TABLE "callsafehandles" ADD CONSTRAINT "callsafelinks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."callsafeusers"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "discoms" ADD CONSTRAINT "discoms_state_slug_fkey" FOREIGN KEY ("state_slug") REFERENCES "public"."state_subsidies"("state_slug") ON DELETE no action ON UPDATE no action;
ALTER TABLE "geo_locations" ADD CONSTRAINT "geo_locations_country_code_fkey" FOREIGN KEY ("country_code") REFERENCES "public"."countries"("code") ON DELETE no action ON UPDATE no action;
ALTER TABLE "in_blog_posts" ADD CONSTRAINT "in_blog_posts_author_slug_fkey" FOREIGN KEY ("author_slug") REFERENCES "public"."authors"("slug") ON DELETE no action ON UPDATE no action;
ALTER TABLE "in_proposals" ADD CONSTRAINT "proposals_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "public"."leaddata"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "in_user_feedback" ADD CONSTRAINT "in_user_feedback_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."in_user"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "leaddata" ADD CONSTRAINT "leaddata_country_code_fkey" FOREIGN KEY ("country_code") REFERENCES "public"."countries"("code") ON DELETE no action ON UPDATE no action;
ALTER TABLE "legal_acceptances" ADD CONSTRAINT "legal_acceptances_policy_id_fkey" FOREIGN KEY ("policy_id") REFERENCES "public"."legal_policies"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "legal_acceptances" ADD CONSTRAINT "legal_acceptances_country_code_fkey" FOREIGN KEY ("country_code") REFERENCES "public"."countries"("code") ON DELETE no action ON UPDATE no action;
ALTER TABLE "legal_acceptances" ADD CONSTRAINT "legal_acceptances_business_fkey" FOREIGN KEY ("country_code","business_id") REFERENCES "public"."business_accounts"("country_code","source_id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "project_management" ADD CONSTRAINT "projectmanagement_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "public"."leaddata"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "solar_products" ADD CONSTRAINT "solar_products_brand_slug_fkey" FOREIGN KEY ("brand_slug") REFERENCES "public"."solar_brands"("slug") ON DELETE no action ON UPDATE no action;
CREATE INDEX "business_accounts_login_email_idx" ON "business_accounts" USING btree ("country_code","login_email");
CREATE INDEX "business_accounts_magic_token_idx" ON "business_accounts" USING btree ("country_code","magic_link_token");
CREATE INDEX "business_profiles_country_slug_idx" ON "business_profiles" USING btree ("country_code","slug");
CREATE INDEX "business_profiles_geo_idx" ON "business_profiles" USING btree ("country_code","level2","isvisible");
CREATE UNIQUE INDEX "callsafe_unsubscribe_email_idx" ON "callsafe_unsubscribe" USING btree ("email");
CREATE INDEX "chatbotmessagesstore_session_idx" ON "chatbotmessagesstore" USING btree ("session_id","timestamp");
CREATE INDEX "data_access_requests_status_idx" ON "data_access_requests" USING btree ("status");
CREATE INDEX "geo_locations_level2_idx" ON "geo_locations" USING btree ("country_code","level1_slug","level2_slug");
CREATE INDEX "leaddata_country_created_idx" ON "leaddata" USING btree ("country_code","created_at");
CREATE INDEX "legal_acceptances_business_policy_idx" ON "legal_acceptances" USING btree ("country_code","business_id","policy_id","accepted_at");
CREATE INDEX "idx_earlier_to_earlier_date" ON "masterlist_indian_businesses" USING btree ("earlier_to_earlier_date");
CREATE INDEX "idx_empanelled_vendor" ON "masterlist_indian_businesses" USING btree ("empanelled_vendor");
CREATE UNIQUE INDEX "idx_masterlist_vendor_id" ON "masterlist_indian_businesses" USING btree ("vendor_id") WHERE (vendor_id IS NOT NULL);
CREATE INDEX "idx_number_of_emails_sent" ON "masterlist_indian_businesses" USING btree ("number_of_emails_sent");
CREATE INDEX "idx_recipient_email" ON "masterlist_indian_businesses" USING btree ("recipient_email");
CREATE INDEX "idx_state" ON "masterlist_indian_businesses" USING btree ("state");
CREATE INDEX "idx_unsubscribe" ON "masterlist_indian_businesses" USING btree ("unsubscribe");
CREATE INDEX "idx_verified" ON "masterlist_indian_businesses" USING btree ("verified");
CREATE INDEX "idx_county" ON "masterlist_usa_businesses" USING btree ("county");
CREATE INDEX "idx_earlier_to_earlier_date_usa" ON "masterlist_usa_businesses" USING btree ("earlier_to_earlier_date");
CREATE INDEX "idx_number_of_emails_sent_usa" ON "masterlist_usa_businesses" USING btree ("number_of_emails_sent");
CREATE INDEX "idx_recipient_email_usa" ON "masterlist_usa_businesses" USING btree ("recipient_email");
CREATE INDEX "idx_state_usa" ON "masterlist_usa_businesses" USING btree ("state");
CREATE INDEX "idx_unsubscribe_usa" ON "masterlist_usa_businesses" USING btree ("unsubscribe");
CREATE INDEX "idx_verified_usa" ON "masterlist_usa_businesses" USING btree ("verified");
CREATE INDEX "rate_limits_reset_time_idx" ON "rate_limits" USING btree ("reset_time");
CREATE INDEX "idx_seo_pages_pillar" ON "seo_pages" USING btree ("pillar_slug");
CREATE INDEX "idx_seo_pages_type" ON "seo_pages" USING btree ("page_type");
