export const cities = [
	// 'Chhatrapati Sambhajinagar',
	// 'Kolhapur',
	// 'Mumbai Suburban',
	// 'Nagpur',
	// 'Nanded',
	// 'Nashik',
	// 'Pune',
	'Sangli'
];

// allcities = ['Ahmednagar',
//     'Akola',
//     'Amravati',
//     'Beed',
//     'Bhandara',
//     'Buldhana',
//     'Chandrapur',
//     'Chhatrapati Sambhajinagar',
//     'Dharashiv',
//     'Dhule',
//     'Gadchiroli',
//     'Gondia',
//     'Hingoli',
//     'Jalgaon',
//     'Jalna',
//     'Kolhapur',
//     'Latur',
//     'Mumbai Suburban',
//     'Nagpur',
//     'Nanded',
//     'Nandurbar',
//     'Nashik',
//     'Palghar',
//     'Parbhani',
//     'Pune',
//     'Raigad',
//     'Ratnagiri',
//     'Sangli',
//     'Satara',
//     'Sindhudurg',
//     'Solapur',
//     'Thane',
//     'Wardha',
//     'Washim',
//     'Yavatmal'];

// To get updated list, use following  query in the database
// 'SELECT DISTINCT district FROM businesses_1 ORDER BY district ASC'
