// Barrel for the introspected schema.
//
// schema.ts and relations.ts are GENERATED by `npm run pull -w @solar/db`.
// Do not hand-edit them — the database (built by the numbered SQL migrations
// in apps/main-app/src/lib/server/migrations/) is the source of truth, and the
// next pull overwrites both files.

export * from './schema';
export * from './relations';
